#ifndef _CLASSIFICATION_DEFS_H_
#define _CLASSIFICATION_DEFS_H_

#define CLASSIFIER_ID_PLS "PLS_OAA"
#define CLASSIFIER_ID_QDA "QDA"
#define CLASSIFIER_ID_KNN "KNN"
#define CLASSIFIER_ID_SVM "SVM"

#endif